[zh-cn]
  languageName = "简体中文"
  weight = 1
  contentDir = "content/zh-cn"

# [en]
#   languageName = "English"
#   weight = 3
#   contentDir = "content/en"

# [zh-tw]
#   languageName = "繁體中文"
#   weight = 5
#   contentDir = "content/zh-tw"
