email = "windyboy@gmail.com"
# facebook = "yourfacebookusername"
github = "windyboy"
# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
twitter = "windysylph"
weibo = "windysylph"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
reddit = "windysylph"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
